FROM mcr.microsoft.com/vscode/devcontainers/universal:latest

# 1) Create non-root user w205:1001, install dev tools
RUN groupadd -g 1001 mids \
 && useradd -m -u 1001 -g 1001 -s /bin/bash w205 \
 && apt-get update \
 && apt-get install -y --no-install-recommends \
    sudo git curl build-essential \
    libssl-dev zlib1g-dev libbz2-dev \
    libreadline-dev libsqlite3-dev llvm \
    libncurses5-dev libncursesw5-dev \
    xz-utils tk-dev \
 && echo "w205 ALL=(ALL) NOPASSWD:ALL" > /etc/sudoers.d/w205 \
 && chmod 0440 /etc/sudoers.d/w205 \
 && apt-get clean \
 && rm -rf /var/lib/apt/lists/*

# 2) Install VS Code CLI from Microsoft repo
RUN apt-get update \
 && apt-get install -y --no-install-recommends \
    wget apt-transport-https gnupg \
 && wget -qO- https://packages.microsoft.com/keys/microsoft.asc \
      | gpg --dearmor >/usr/share/keyrings/packages.microsoft.gpg \
 && echo "deb [arch=amd64 signed-by=/usr/share/keyrings/packages.microsoft.gpg] \
      https://packages.microsoft.com/repos/code stable main" \
      > /etc/apt/sources.list.d/vscode.list \
 && apt-get update \
 && apt-get install -y --no-install-recommends code \
 && apt-get clean \
 && rm -rf /var/lib/apt/lists/*

# # 3) Switch to non-root for pyenv & Poetry
# USER w205
# ENV PYENV_ROOT=/home/w205/.pyenv \
#     PATH=/home/w205/.pyenv/bin:/home/w205/.pyenv/shims:$PATH

# # 4) Install pyenv and Python 3.10.12
# RUN git clone https://github.com/pyenv/pyenv.git $PYENV_ROOT \
#  && echo 'export PYENV_ROOT="$HOME/.pyenv"' >> ~/.bashrc \
#  && echo 'export PATH="$PYENV_ROOT/bin:$PATH"' >> ~/.bashrc \
#  && echo 'eval "$(pyenv init --path)"' >> ~/.bashrc \
#  && sudo apt-get update \
#  && sudo apt-get install -y --no-install-recommends \
#       build-essential libssl-dev zlib1g-dev \
#       libbz2-dev libreadline-dev libsqlite3-dev \
#       curl llvm libncurses5-dev libncursesw5-dev \
#       xz-utils tk-dev \
#  && pyenv install 3.10.12 \
#  && pyenv global 3.10.12

# # 5) Install Poetry
# RUN curl -sSL https://install.python-poetry.org | python3 - \
#  && echo 'export PATH="$HOME/.local/bin:$PATH"' >> ~/.bashrc

# 6) Fix NVM ownership so w205 can manage it
USER root
RUN chown -R w205:1001 /usr/local/share/nvm

# 7) Install SSH client and Postgres client
RUN sudo apt-get update \
 && sudo apt-get install -y --no-install-recommends postgresql-client openssh-client

# 8) Start SSH on container start via bashrc
# RUN echo 'service ssh start' >> ~/.bashrc # This was for root's bashrc.
                                            # If you still need SSH, you might need to reconsider how it's started,
                                            # especially if the default shell for w205 becomes zsh.
                                            # For now, I'll comment it out as the code tunnel might be your primary access.


# SECTION 9: Install Zsh, Oh My Zsh, Powerlevel10k, and plugins
USER root
# Install Zsh and basic fonts (Powerlevel10k might need more specific Nerd Fonts for all glyphs)
RUN apt-get update && apt-get install -y zsh fonts-powerline \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*
# Set Zsh as default shell for the w205 user
RUN chsh -s $(which zsh) w205

USER w205
# Install Oh My Zsh (non-interactively)
RUN sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)" "" --unattended
# Install Powerlevel10k theme for Oh My Zsh
RUN git clone --depth=1 https://github.com/romkatv/powerlevel10k.git ${ZSH_CUSTOM:-$HOME/.oh-my-zsh/custom}/themes/powerlevel10k
# Install zsh-autosuggestions plugin for Oh My Zsh
RUN git clone https://github.com/zsh-users/zsh-autosuggestions ${ZSH_CUSTOM:-$HOME/.oh-my-zsh/custom}/plugins/zsh-autosuggestions

# Corrected .zshrc modifications
RUN sed -i 's/^ZSH_THEME=".*"/ZSH_THEME="powerlevel10k\/powerlevel10k"/' $HOME/.zshrc && \
    sed -i 's/^plugins=(git zsh-autosuggestions pyenv)/plugins=(git zsh-autosuggestions)/' $HOME/.zshrc && \
    echo '\n# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.' >> $HOME/.zshrc && \
    echo '[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh' >> $HOME/.zshrc

# 10) Set env vars for services
ENV ANACONDA_HOST=anaconda \
    ANACONDA_PORT=8888 \
    POSTGRES_HOST=postgres \
    POSTGRES_PORT=5432

# 11) Final default user
USER w205

