version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    command:
      - "code"
      - "tunnel"
      - "--name"
      - "w205-devcontainer"
      - "--accept-server-license-terms"
    volumes:
      - /home/w205/user:/workspace/user # Your .ipynb files are here, accessible to the app
      - /home/w205/backups:/workspace/backups # Backup directory
      - /home/w205/docker:/workspace/docker # Docker directory:
      - /home/w205/scripts:/workspace/scripts # Scripts directory
      - /home/w205/temp:/workspace/temp # Temporary files directory

    working_dir: /workspace
    stdin_open: true
    tty: true
    depends_on:
      - anaconda
      - postgres
    environment:
      ANACONDA_HOST: anaconda
      ANACONDA_PORT: 8888
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432

  postgres:
    image: w205_postgres
    command: postgres -c 'shared_buffers=1GB'
    shm_size: '1GB'
    stdin_open: true
    tty: true
    environment:
      POSTGRES_PASSWORD: ucb
    volumes:
      - /home/w205/user:/user # Your .ipynb files are here, accessible to postgres if needed
      # This uses a host path for postgres data, which is also fine.
      # If you wanted to use a named volume like 'w205_postgres_data' instead, you'd change it to:
      # - w205_postgres_data:/var/lib/postgresql/data
      - /home/w205/docker/mounts/postgres/data:/var/lib/postgresql/data
    expose:
      - "5432"
    ports:
      - "5432:5432"
    extra_hosts:
      - "localhost:127.0.0.1"

  anaconda:
    image: w205_anaconda
    stdin_open: true
    tty: true
    command:
      - "jupyter"
      - "notebook"
      - "--ip=0.0.0.0"
      - "--port=8888"
      - "--no-browser"
      - "--allow-root"
      - "--NotebookApp.token="
      - "--NotebookApp.password="
      - "--NotebookApp.certfile="
      - "--NotebookApp.keyfile="
      - "--NotebookApp.allow_origin=*"
      - "--NotebookApp.notebook_dir=/user"
    volumes:
      - /home/w205/user:/user # Your .ipynb files are here, accessible to anaconda
      - /home/w205/docker/mounts/anaconda/environments:/opt/conda/envs # Persisted conda envs
    expose:
      - "8888"
      - "443"
    ports:
      - "8888:8888"
      - "443:443"

networks:
  default:
    driver: bridge