version: '3.8'

services:

  postgres:
    image: w205_postgres
    command: postgres -c 'shared_buffers=1GB'
    shm_size: '1GB'
    stdin_open: true
    tty: true
    environment:
      POSTGRES_PASSWORD: ucb
    volumes:
      - /home/w205/user:/user
      - /home/w205/docker/mounts/postgres/data:/var/lib/postgresql/data
    expose:
      - "5432"
    ports:
      - "5432:5432"
    extra_hosts:
      - "localhost:127.0.0.1"

  anaconda:
    image: w205_anaconda
    stdin_open: true
    tty: true
    volumes:
      - /home/w205/user:/user
      - /home/w205/docker/mounts/anaconda/environments:/opt/conda/envs
    expose:
      - "8888"
      - "443"
    ports:
      - "8888:8888"
      - "443:443"

